'use strict';

const PERSISTENCE_STORE = Object.freeze({
  MONGOOSE: 'mongoose',
  POSTGRES: 'postgres',
});

const PERSISTENCE_DOMAIN = Object.freeze({
  AUTHORITY: 'authority',
  CHALLENGES: 'challenges',
  COURSES: 'courses',
  IDEAS: 'ideas',
  IDENTITY: 'identity',
  INTEGRATIONS: 'integrations',
  LEARNING: 'learning',
  ORGANIZATIONS: 'organizations',
  SOCIAL: 'social',
});

const DOMAIN_ENVIRONMENT_KEYS = Object.freeze({
  [PERSISTENCE_DOMAIN.AUTHORITY]: 'PERSISTENCE_AUTHORITY_STORE',
  [PERSISTENCE_DOMAIN.CHALLENGES]: 'PERSISTENCE_CHALLENGES_STORE',
  [PERSISTENCE_DOMAIN.COURSES]: 'PERSISTENCE_COURSES_STORE',
  [PERSISTENCE_DOMAIN.IDEAS]: 'PERSISTENCE_IDEAS_STORE',
  [PERSISTENCE_DOMAIN.IDENTITY]: 'PERSISTENCE_IDENTITY_STORE',
  [PERSISTENCE_DOMAIN.INTEGRATIONS]: 'PERSISTENCE_INTEGRATIONS_STORE',
  [PERSISTENCE_DOMAIN.LEARNING]: 'PERSISTENCE_LEARNING_STORE',
  [PERSISTENCE_DOMAIN.ORGANIZATIONS]: 'PERSISTENCE_ORGANIZATIONS_STORE',
  [PERSISTENCE_DOMAIN.SOCIAL]: 'PERSISTENCE_SOCIAL_STORE',
});

const CORE_AUTHORITY_DOMAINS = Object.freeze(
  [
    PERSISTENCE_DOMAIN.AUTHORITY,
    PERSISTENCE_DOMAIN.IDENTITY,
    PERSISTENCE_DOMAIN.ORGANIZATIONS,
  ].sort(),
);

// These repositories have a complete PostgreSQL implementation in P0C-S5. Direct-Mongoose
// feature routes remain explicitly ineligible until their owning phase introduces a service boundary.
const POSTGRES_RUNTIME_READY_DOMAINS = Object.freeze(new Set(CORE_AUTHORITY_DOMAINS));

module.exports = {
  CORE_AUTHORITY_DOMAINS,
  DOMAIN_ENVIRONMENT_KEYS,
  PERSISTENCE_DOMAIN,
  PERSISTENCE_STORE,
  POSTGRES_RUNTIME_READY_DOMAINS,
};
