'use strict';

const { PLATFORM_ROLE } = require('../identity/contracts');
const { COURSE_STAFF_ROLE, ORGANIZATION_ROLE } = require('../organizations/contracts');

function freezeList(values) {
  return Object.freeze([...values]);
}

function freezeGrantMap(grants) {
  return Object.freeze(
    Object.fromEntries(Object.entries(grants).map(([role, values]) => [role, freezeList(values)])),
  );
}

const PERMISSION = Object.freeze({
  BREAK_GLASS_REQUEST: 'break_glass:request',
  COURSE_ANALYTICS_READ: 'courses:analytics:read',
  COURSE_CREATE: 'courses:create',
  COURSE_DRAFT_READ: 'courses:draft:read',
  COURSE_DRAFT_WRITE: 'courses:draft:write',
  COURSE_ENROLLMENTS_MANAGE: 'courses:enrollments:manage',
  COURSE_GRADE: 'courses:grade',
  COURSE_LEARNERS_READ: 'courses:learners:read',
  COURSE_PAYMENT_REVIEW: 'courses:payments:review',
  COURSE_PUBLISH: 'courses:publish',
  COURSE_STAFF_MANAGE: 'courses:staff:manage',
  COURSE_SUBMISSIONS_READ: 'courses:submissions:read',
  MODERATION_ACTION_CREATE: 'moderation:actions:create',
  MODERATION_CASE_READ: 'moderation:cases:read',
  OAUTH_CLIENT_AUTHORIZE_SELF: 'oauth_clients:authorize:self',
  ORGANIZATION_ANALYTICS_READ: 'organizations:analytics:read',
  ORGANIZATION_CREATE: 'organizations:create',
  ORGANIZATION_MEMBERS_MANAGE: 'organizations:members:manage',
  ORGANIZATION_MEMBERS_READ: 'organizations:members:read',
  ORGANIZATION_OWNERSHIP_TRANSFER: 'organizations:ownership:transfer',
  ORGANIZATION_READ_PRIVATE: 'organizations:read:private',
  ORGANIZATION_UPDATE: 'organizations:update',
  ORGANIZATION_VERIFICATION_REVIEW: 'organizations:verification:review',
  ORGANIZATION_VERIFICATION_SUBMIT: 'organizations:verification:submit',
  PLATFORM_ACCOUNT_STATUS_MANAGE: 'platform:account_status:manage',
  PLATFORM_AUDIT_READ: 'platform:audit:read',
  PLATFORM_ROLE_MANAGE: 'platform:roles:manage',
  PLATFORM_USERS_READ: 'platform:users:read',
  PROFILE_READ_SELF: 'profile:read:self',
  PROFILE_WRITE_SELF: 'profile:write:self',
  SESSION_LIST_SELF: 'sessions:list:self',
  SESSION_REVOKE_ALL_SELF: 'sessions:revoke_all:self',
  SESSION_REVOKE_SELF: 'sessions:revoke:self',
  SUPPORT_ACCOUNT_READ: 'support:accounts:read',
});

const BASE_AUTHENTICATED_PERMISSIONS = freezeList([
  PERMISSION.OAUTH_CLIENT_AUTHORIZE_SELF,
  PERMISSION.ORGANIZATION_CREATE,
  PERMISSION.PROFILE_READ_SELF,
  PERMISSION.PROFILE_WRITE_SELF,
  PERMISSION.SESSION_LIST_SELF,
  PERMISSION.SESSION_REVOKE_ALL_SELF,
  PERMISSION.SESSION_REVOKE_SELF,
]);

const PLATFORM_ROLE_PERMISSIONS = freezeGrantMap({
  [PLATFORM_ROLE.LEARNER]: [],
  [PLATFORM_ROLE.MODERATOR]: [PERMISSION.MODERATION_ACTION_CREATE, PERMISSION.MODERATION_CASE_READ],
  [PLATFORM_ROLE.SUPERADMIN]: [
    PERMISSION.BREAK_GLASS_REQUEST,
    PERMISSION.MODERATION_ACTION_CREATE,
    PERMISSION.MODERATION_CASE_READ,
    PERMISSION.ORGANIZATION_VERIFICATION_REVIEW,
    PERMISSION.PLATFORM_ACCOUNT_STATUS_MANAGE,
    PERMISSION.PLATFORM_AUDIT_READ,
    PERMISSION.PLATFORM_ROLE_MANAGE,
    PERMISSION.PLATFORM_USERS_READ,
  ],
  [PLATFORM_ROLE.SUPPORT]: [PERMISSION.SUPPORT_ACCOUNT_READ],
});

const ORGANIZATION_ROLE_PERMISSIONS = freezeGrantMap({
  [ORGANIZATION_ROLE.OWNER]: [
    PERMISSION.COURSE_ANALYTICS_READ,
    PERMISSION.COURSE_CREATE,
    PERMISSION.COURSE_DRAFT_READ,
    PERMISSION.COURSE_DRAFT_WRITE,
    PERMISSION.COURSE_ENROLLMENTS_MANAGE,
    PERMISSION.COURSE_GRADE,
    PERMISSION.COURSE_LEARNERS_READ,
    PERMISSION.COURSE_PUBLISH,
    PERMISSION.COURSE_STAFF_MANAGE,
    PERMISSION.COURSE_SUBMISSIONS_READ,
    PERMISSION.ORGANIZATION_ANALYTICS_READ,
    PERMISSION.ORGANIZATION_MEMBERS_MANAGE,
    PERMISSION.ORGANIZATION_MEMBERS_READ,
    PERMISSION.ORGANIZATION_OWNERSHIP_TRANSFER,
    PERMISSION.ORGANIZATION_READ_PRIVATE,
    PERMISSION.ORGANIZATION_UPDATE,
    PERMISSION.ORGANIZATION_VERIFICATION_SUBMIT,
  ],
  [ORGANIZATION_ROLE.ADMIN]: [
    PERMISSION.COURSE_ANALYTICS_READ,
    PERMISSION.COURSE_CREATE,
    PERMISSION.COURSE_DRAFT_READ,
    PERMISSION.COURSE_DRAFT_WRITE,
    PERMISSION.COURSE_ENROLLMENTS_MANAGE,
    PERMISSION.COURSE_GRADE,
    PERMISSION.COURSE_LEARNERS_READ,
    PERMISSION.COURSE_PUBLISH,
    PERMISSION.COURSE_STAFF_MANAGE,
    PERMISSION.COURSE_SUBMISSIONS_READ,
    PERMISSION.ORGANIZATION_ANALYTICS_READ,
    PERMISSION.ORGANIZATION_MEMBERS_MANAGE,
    PERMISSION.ORGANIZATION_MEMBERS_READ,
    PERMISSION.ORGANIZATION_READ_PRIVATE,
    PERMISSION.ORGANIZATION_UPDATE,
    PERMISSION.ORGANIZATION_VERIFICATION_SUBMIT,
  ],
  [ORGANIZATION_ROLE.INSTRUCTOR]: [PERMISSION.ORGANIZATION_READ_PRIVATE],
  [ORGANIZATION_ROLE.GRADER]: [PERMISSION.ORGANIZATION_READ_PRIVATE],
  [ORGANIZATION_ROLE.ANALYST]: [
    PERMISSION.ORGANIZATION_ANALYTICS_READ,
    PERMISSION.ORGANIZATION_READ_PRIVATE,
  ],
});

const COURSE_STAFF_ROLE_PERMISSIONS = freezeGrantMap({
  [COURSE_STAFF_ROLE.MANAGER]: [
    PERMISSION.COURSE_ANALYTICS_READ,
    PERMISSION.COURSE_DRAFT_READ,
    PERMISSION.COURSE_DRAFT_WRITE,
    PERMISSION.COURSE_ENROLLMENTS_MANAGE,
    PERMISSION.COURSE_GRADE,
    PERMISSION.COURSE_LEARNERS_READ,
    PERMISSION.COURSE_PUBLISH,
    PERMISSION.COURSE_STAFF_MANAGE,
    PERMISSION.COURSE_SUBMISSIONS_READ,
  ],
  [COURSE_STAFF_ROLE.INSTRUCTOR]: [
    PERMISSION.COURSE_DRAFT_READ,
    PERMISSION.COURSE_DRAFT_WRITE,
    PERMISSION.COURSE_LEARNERS_READ,
    PERMISSION.COURSE_SUBMISSIONS_READ,
  ],
  [COURSE_STAFF_ROLE.GRADER]: [
    PERMISSION.COURSE_DRAFT_READ,
    PERMISSION.COURSE_GRADE,
    PERMISSION.COURSE_LEARNERS_READ,
    PERMISSION.COURSE_SUBMISSIONS_READ,
  ],
  [COURSE_STAFF_ROLE.ANALYST]: [PERMISSION.COURSE_ANALYTICS_READ],
  [COURSE_STAFF_ROLE.PAYMENT_REVIEWER]: [PERMISSION.COURSE_PAYMENT_REVIEW],
});

const ORGANIZATION_ROLE_ALLOWED_COURSE_ROLES = freezeGrantMap({
  [ORGANIZATION_ROLE.OWNER]: Object.values(COURSE_STAFF_ROLE),
  [ORGANIZATION_ROLE.ADMIN]: Object.values(COURSE_STAFF_ROLE),
  [ORGANIZATION_ROLE.INSTRUCTOR]: [COURSE_STAFF_ROLE.INSTRUCTOR],
  [ORGANIZATION_ROLE.GRADER]: [COURSE_STAFF_ROLE.GRADER],
  [ORGANIZATION_ROLE.ANALYST]: [COURSE_STAFF_ROLE.ANALYST],
});

const SELF_SCOPED_PERMISSIONS = freezeList([
  PERMISSION.OAUTH_CLIENT_AUTHORIZE_SELF,
  PERMISSION.PROFILE_READ_SELF,
  PERMISSION.PROFILE_WRITE_SELF,
  PERMISSION.SESSION_LIST_SELF,
  PERMISSION.SESSION_REVOKE_ALL_SELF,
  PERMISSION.SESSION_REVOKE_SELF,
]);

const ORGANIZATION_SCOPED_PERMISSIONS = freezeList([
  PERMISSION.ORGANIZATION_ANALYTICS_READ,
  PERMISSION.ORGANIZATION_MEMBERS_MANAGE,
  PERMISSION.ORGANIZATION_MEMBERS_READ,
  PERMISSION.ORGANIZATION_OWNERSHIP_TRANSFER,
  PERMISSION.ORGANIZATION_READ_PRIVATE,
  PERMISSION.ORGANIZATION_UPDATE,
  PERMISSION.ORGANIZATION_VERIFICATION_SUBMIT,
]);

const COURSE_SCOPED_PERMISSIONS = freezeList([
  PERMISSION.COURSE_ANALYTICS_READ,
  PERMISSION.COURSE_CREATE,
  PERMISSION.COURSE_DRAFT_READ,
  PERMISSION.COURSE_DRAFT_WRITE,
  PERMISSION.COURSE_ENROLLMENTS_MANAGE,
  PERMISSION.COURSE_GRADE,
  PERMISSION.COURSE_LEARNERS_READ,
  PERMISSION.COURSE_PAYMENT_REVIEW,
  PERMISSION.COURSE_PUBLISH,
  PERMISSION.COURSE_STAFF_MANAGE,
  PERMISSION.COURSE_SUBMISSIONS_READ,
]);

const VERIFIED_EMAIL_PERMISSIONS = freezeList([
  PERMISSION.OAUTH_CLIENT_AUTHORIZE_SELF,
  PERMISSION.ORGANIZATION_CREATE,
  PERMISSION.ORGANIZATION_MEMBERS_MANAGE,
  PERMISSION.ORGANIZATION_VERIFICATION_SUBMIT,
  PERMISSION.COURSE_PAYMENT_REVIEW,
  PERMISSION.COURSE_PUBLISH,
]);

const RECENT_AUTHENTICATION_PERMISSIONS = freezeList([
  PERMISSION.BREAK_GLASS_REQUEST,
  PERMISSION.ORGANIZATION_OWNERSHIP_TRANSFER,
  PERMISSION.ORGANIZATION_VERIFICATION_REVIEW,
  PERMISSION.PLATFORM_ACCOUNT_STATUS_MANAGE,
  PERMISSION.PLATFORM_ROLE_MANAGE,
  PERMISSION.SESSION_REVOKE_ALL_SELF,
]);

const APPROVED_ORGANIZATION_PERMISSIONS = freezeList([
  PERMISSION.COURSE_ENROLLMENTS_MANAGE,
  PERMISSION.COURSE_PAYMENT_REVIEW,
  PERMISSION.COURSE_PUBLISH,
]);

const KNOWN_PERMISSIONS = freezeList(Object.values(PERMISSION));

module.exports = {
  APPROVED_ORGANIZATION_PERMISSIONS,
  BASE_AUTHENTICATED_PERMISSIONS,
  COURSE_SCOPED_PERMISSIONS,
  COURSE_STAFF_ROLE_PERMISSIONS,
  KNOWN_PERMISSIONS,
  ORGANIZATION_ROLE_ALLOWED_COURSE_ROLES,
  ORGANIZATION_ROLE_PERMISSIONS,
  ORGANIZATION_SCOPED_PERMISSIONS,
  PERMISSION,
  PLATFORM_ROLE_PERMISSIONS,
  RECENT_AUTHENTICATION_PERMISSIONS,
  SELF_SCOPED_PERMISSIONS,
  VERIFIED_EMAIL_PERMISSIONS,
};
