'use strict';

const { requestSchemas, responseSchemas } = require('./contracts');

const SECURITY = Object.freeze({
  BEARER: Object.freeze([{ bearerAuth: [] }]),
  OPTIONAL_BEARER: Object.freeze([{}, { bearerAuth: [] }]),
  PUBLIC: Object.freeze([]),
  REFRESH_CSRF: Object.freeze([{ csrfHeader: [], refreshCookie: [] }]),
});

function operation({
  acceptsBody = false,
  id,
  method,
  path,
  request,
  response,
  security = SECURITY.BEARER,
  status = 200,
  summary,
  tags,
}) {
  return Object.freeze({
    acceptsBody,
    id,
    method,
    path,
    request,
    response,
    security,
    status,
    summary,
    tags: Object.freeze(tags),
  });
}

const operations = Object.freeze([
  operation({
    id: 'getOpenApiDocument',
    method: 'get',
    path: '/openapi.json',
    request: requestSchemas.noInput,
    response: responseSchemas.openApi,
    security: SECURITY.PUBLIC,
    summary: 'Get the executable OpenAPI 3.1 contract',
    tags: ['Operations'],
  }),
  operation({
    id: 'getLiveness',
    method: 'get',
    path: '/health/live',
    request: requestSchemas.noInput,
    response: responseSchemas.health,
    security: SECURITY.PUBLIC,
    summary: 'Report process liveness without dependency detail',
    tags: ['Operations'],
  }),
  operation({
    id: 'getReadiness',
    method: 'get',
    path: '/health/ready',
    request: requestSchemas.noInput,
    response: responseSchemas.health,
    security: SECURITY.PUBLIC,
    summary: 'Report aggregate serving readiness',
    tags: ['Operations'],
  }),
  operation({
    id: 'getDependencyReadiness',
    method: 'get',
    path: '/health/dependencies',
    request: requestSchemas.noInput,
    response: responseSchemas.healthDependencies,
    summary: 'Report redacted dependency states to a superadmin',
    tags: ['Operations'],
  }),
  operation({
    acceptsBody: true,
    id: 'register',
    method: 'post',
    path: '/auth/register',
    request: requestSchemas.identityRegister,
    response: responseSchemas.accessSession,
    security: SECURITY.PUBLIC,
    status: 201,
    summary: 'Create a learner account and web session',
    tags: ['Identity'],
  }),
  operation({
    acceptsBody: true,
    id: 'login',
    method: 'post',
    path: '/auth/login',
    request: requestSchemas.identityLogin,
    response: responseSchemas.accessSession,
    security: SECURITY.PUBLIC,
    summary: 'Create a web session with local credentials',
    tags: ['Identity'],
  }),
  operation({
    id: 'refreshSession',
    method: 'post',
    path: '/auth/refresh',
    request: requestSchemas.empty,
    response: responseSchemas.accessSession,
    security: SECURITY.REFRESH_CSRF,
    summary: 'Rotate the refresh token and issue an access token',
    tags: ['Identity'],
  }),
  operation({
    id: 'logout',
    method: 'post',
    path: '/auth/logout',
    request: requestSchemas.empty,
    security: SECURITY.REFRESH_CSRF,
    status: 204,
    summary: 'Revoke the current refresh session',
    tags: ['Identity'],
  }),
  operation({
    id: 'logoutAll',
    method: 'post',
    path: '/auth/logout-all',
    request: requestSchemas.empty,
    status: 204,
    summary: 'Revoke every session for the authenticated user',
    tags: ['Identity'],
  }),
  operation({
    id: 'requestEmailVerification',
    method: 'post',
    path: '/auth/email/verify/request',
    request: requestSchemas.empty,
    response: responseSchemas.message,
    status: 202,
    summary: 'Queue an email-verification token when needed',
    tags: ['Identity'],
  }),
  operation({
    acceptsBody: true,
    id: 'confirmEmailVerification',
    method: 'post',
    path: '/auth/email/verify/confirm',
    request: requestSchemas.identityConfirmToken,
    response: responseSchemas.user,
    security: SECURITY.PUBLIC,
    summary: 'Consume an email-verification token',
    tags: ['Identity'],
  }),
  operation({
    acceptsBody: true,
    id: 'requestPasswordReset',
    method: 'post',
    path: '/auth/password/forgot',
    request: requestSchemas.identityForgotPassword,
    response: responseSchemas.message,
    security: SECURITY.PUBLIC,
    status: 202,
    summary: 'Queue a password-reset token without account disclosure',
    tags: ['Identity'],
  }),
  operation({
    acceptsBody: true,
    id: 'resetPassword',
    method: 'post',
    path: '/auth/password/reset',
    request: requestSchemas.identityResetPassword,
    security: SECURITY.PUBLIC,
    status: 204,
    summary: 'Consume a password-reset token and revoke sessions',
    tags: ['Identity'],
  }),
  operation({
    id: 'startGoogleLogin',
    method: 'get',
    path: '/auth/google/start',
    request: requestSchemas.googleStart,
    security: SECURITY.PUBLIC,
    status: 302,
    summary: 'Begin the Google authorization-code flow',
    tags: ['Identity'],
  }),
  operation({
    id: 'completeGoogleLogin',
    method: 'get',
    path: '/auth/google/callback',
    request: requestSchemas.googleCallback,
    security: SECURITY.PUBLIC,
    status: 302,
    summary: 'Complete the Google authorization-code flow',
    tags: ['Identity'],
  }),
  operation({
    id: 'getMe',
    method: 'get',
    path: '/me',
    request: requestSchemas.noInput,
    response: responseSchemas.user,
    summary: 'Get the authenticated user',
    tags: ['Identity'],
  }),
  operation({
    id: 'getMyTheme',
    method: 'get',
    path: '/me/preferences/theme',
    request: requestSchemas.noInput,
    response: responseSchemas.themePreferences,
    summary: 'Get the authenticated user theme preferences',
    tags: ['Identity'],
  }),
  operation({
    acceptsBody: true,
    id: 'updateMyTheme',
    method: 'put',
    path: '/me/preferences/theme',
    request: requestSchemas.themePreferences,
    response: responseSchemas.themePreferences,
    summary: 'Update the authenticated user theme preferences',
    tags: ['Identity'],
  }),
  operation({
    id: 'listMySessions',
    method: 'get',
    path: '/me/sessions',
    request: requestSchemas.noInput,
    response: responseSchemas.sessions,
    summary: 'List sessions for the authenticated user',
    tags: ['Identity'],
  }),
  operation({
    id: 'revokeMySession',
    method: 'delete',
    path: '/me/sessions/{sessionId}',
    request: requestSchemas.sessionId,
    status: 204,
    summary: 'Revoke one owned session',
    tags: ['Identity'],
  }),
  operation({
    id: 'listMyOrganizations',
    method: 'get',
    path: '/organizations',
    request: requestSchemas.noInput,
    response: responseSchemas.organizations,
    summary: 'List active organization memberships',
    tags: ['Organizations'],
  }),
  operation({
    acceptsBody: true,
    id: 'createOrganization',
    method: 'post',
    path: '/organizations',
    request: requestSchemas.organizationCreate,
    response: responseSchemas.organizationCreated,
    status: 201,
    summary: 'Create an organization with an owner membership',
    tags: ['Organizations'],
  }),
  operation({
    id: 'acceptOrganizationInvitation',
    method: 'post',
    path: '/organization-invitations/{token}/accept',
    request: requestSchemas.organizationInvitationAccept,
    response: responseSchemas.invitationAccepted,
    summary: 'Accept an organization invitation',
    tags: ['Organizations'],
  }),
  operation({
    id: 'listProviderVerificationReviews',
    method: 'get',
    path: '/admin/provider-verifications',
    request: requestSchemas.organizationReviews,
    response: responseSchemas.reviews,
    summary: 'List provider verification reviews',
    tags: ['Organizations', 'Administration'],
  }),
  operation({
    acceptsBody: true,
    id: 'decideProviderVerification',
    method: 'post',
    path: '/admin/provider-verifications/{reviewId}/decision',
    request: requestSchemas.organizationDecision,
    response: responseSchemas.verification,
    summary: 'Approve or reject a provider verification',
    tags: ['Organizations', 'Administration'],
  }),
  operation({
    id: 'getOrganization',
    method: 'get',
    path: '/organizations/{organizationId}',
    request: requestSchemas.organizationId,
    response: responseSchemas.organization,
    security: SECURITY.OPTIONAL_BEARER,
    summary: 'Get a public or authorized private organization',
    tags: ['Organizations'],
  }),
  operation({
    acceptsBody: true,
    id: 'updateOrganization',
    method: 'patch',
    path: '/organizations/{organizationId}',
    request: requestSchemas.organizationUpdate,
    response: responseSchemas.organization,
    summary: 'Update organization fields with optimistic concurrency',
    tags: ['Organizations'],
  }),
  operation({
    id: 'listOrganizationMembers',
    method: 'get',
    path: '/organizations/{organizationId}/members',
    request: requestSchemas.organizationMembers,
    response: responseSchemas.memberships,
    summary: 'List authorized organization members',
    tags: ['Organizations'],
  }),
  operation({
    acceptsBody: true,
    id: 'inviteOrganizationMember',
    method: 'post',
    path: '/organizations/{organizationId}/invitations',
    request: requestSchemas.organizationInvitation,
    response: responseSchemas.invitation,
    status: 201,
    summary: 'Invite a member into an organization role',
    tags: ['Organizations'],
  }),
  operation({
    acceptsBody: true,
    id: 'updateOrganizationMember',
    method: 'patch',
    path: '/organizations/{organizationId}/members/{userId}',
    request: requestSchemas.organizationMemberMutation,
    response: responseSchemas.membership,
    summary: 'Update an organization membership',
    tags: ['Organizations'],
  }),
  operation({
    id: 'removeOrganizationMember',
    method: 'delete',
    path: '/organizations/{organizationId}/members/{userId}',
    request: {
      body: requestSchemas.empty.body,
      params: requestSchemas.organizationMemberMutation.params,
    },
    status: 204,
    summary: 'Revoke an organization membership',
    tags: ['Organizations'],
  }),
  operation({
    acceptsBody: true,
    id: 'submitProviderVerification',
    method: 'post',
    path: '/organizations/{organizationId}/verification',
    request: requestSchemas.organizationVerification,
    response: responseSchemas.verification,
    status: 201,
    summary: 'Submit an organization for provider verification',
    tags: ['Organizations'],
  }),
  operation({
    id: 'listAuthorityAuditEvents',
    method: 'get',
    path: '/admin/audit-events',
    request: requestSchemas.authorityAuditList,
    response: responseSchemas.auditEvents,
    summary: 'List bounded authority audit events',
    tags: ['Administration'],
  }),
  operation({
    id: 'listAuthorityUsers',
    method: 'get',
    path: '/admin/users',
    request: requestSchemas.authorityUserList,
    response: responseSchemas.authorityUsers,
    summary: 'List bounded platform authority users',
    tags: ['Administration'],
  }),
  operation({
    acceptsBody: true,
    id: 'changePlatformRole',
    method: 'patch',
    path: '/admin/users/{userId}/platform-role',
    request: requestSchemas.authorityRoleChange,
    response: responseSchemas.authorityChange,
    summary: 'Change a platform role with an audited revision check',
    tags: ['Administration'],
  }),
  operation({
    acceptsBody: true,
    id: 'changeAccountStatus',
    method: 'patch',
    path: '/admin/users/{userId}/status',
    request: requestSchemas.authorityStatusChange,
    response: responseSchemas.authorityChange,
    summary: 'Change account status with an audited revision check',
    tags: ['Administration'],
  }),
  operation({
    acceptsBody: true,
    id: 'transferOrganizationOwnership',
    method: 'post',
    path: '/organizations/{organizationId}/ownership-transfer',
    request: requestSchemas.authorityTransfer,
    response: responseSchemas.ownershipTransfer,
    summary: 'Atomically transfer organization ownership',
    tags: ['Administration', 'Organizations'],
  }),
  operation({
    acceptsBody: true,
    id: 'createFileUploadIntent',
    method: 'post',
    path: '/files/upload-intents',
    request: requestSchemas.fileUploadIntent,
    response: responseSchemas.uploadIntent,
    status: 201,
    summary: 'Create a bounded direct-upload intent',
    tags: ['Files'],
  }),
  operation({
    id: 'getFileMetadata',
    method: 'get',
    path: '/files/{fileId}',
    request: requestSchemas.fileId,
    response: responseSchemas.file,
    summary: 'Get authorized file metadata',
    tags: ['Files'],
  }),
  operation({
    id: 'completeFileUpload',
    method: 'post',
    path: '/files/{fileId}/complete',
    request: requestSchemas.fileIdMutation,
    response: responseSchemas.file,
    summary: 'Verify uploaded object metadata before scan',
    tags: ['Files'],
  }),
  operation({
    id: 'createFileDownload',
    method: 'post',
    path: '/files/{fileId}/download',
    request: requestSchemas.fileIdMutation,
    response: responseSchemas.download,
    summary: 'Create a short-lived authorized download grant',
    tags: ['Files'],
  }),
  operation({
    acceptsBody: true,
    id: 'setFileVisibility',
    method: 'patch',
    path: '/files/{fileId}/visibility',
    request: requestSchemas.fileVisibility,
    response: responseSchemas.file,
    summary: 'Change file visibility within its purpose policy',
    tags: ['Files'],
  }),
  operation({
    id: 'deleteFile',
    method: 'delete',
    path: '/files/{fileId}',
    request: requestSchemas.fileIdMutation,
    status: 204,
    summary: 'Revoke access and request object deletion',
    tags: ['Files'],
  }),
  operation({
    id: 'listChallenges',
    method: 'get',
    path: '/challenges',
    request: requestSchemas.challengeList,
    response: responseSchemas.challenges,
    security: SECURITY.PUBLIC,
    summary: 'List published challenges with pagination and filters',
    tags: ['Challenges'],
  }),
  operation({
    id: 'getChallenge',
    method: 'get',
    path: '/challenges/{challengeId}',
    request: requestSchemas.challengeId,
    response: responseSchemas.challenge,
    security: SECURITY.PUBLIC,
    summary: 'Get published challenge details for learner',
    tags: ['Challenges'],
  }),
  operation({
    acceptsBody: true,
    id: 'createChallenge',
    method: 'post',
    path: '/challenges',
    request: requestSchemas.challengeCreate,
    response: responseSchemas.challenge,
    status: 201,
    summary: 'Create draft challenge',
    tags: ['Challenges'],
  }),
  operation({
    id: 'publishChallenge',
    method: 'post',
    path: '/challenges/{challengeId}/publish',
    request: requestSchemas.challengeId,
    response: responseSchemas.challenge,
    summary: 'Publish challenge version',
    tags: ['Challenges'],
  }),
  operation({
    acceptsBody: true,
    id: 'runChallengeCode',
    method: 'post',
    path: '/challenges/{challengeId}/run',
    request: requestSchemas.challengeRun,
    response: responseSchemas.challengeRunResult,
    summary: 'Run learner code against visible test cases',
    tags: ['Challenges'],
  }),
  operation({
    acceptsBody: true,
    id: 'submitChallengeCode',
    method: 'post',
    path: '/challenges/{challengeId}/submit',
    request: requestSchemas.challengeSubmit,
    response: responseSchemas.challengeSubmitResult,
    summary: 'Submit learner code against hidden test suite',
    tags: ['Challenges'],
  }),
  operation({
    id: 'listChallengeSubmissions',
    method: 'get',
    path: '/challenges/{challengeId}/submissions',
    request: requestSchemas.challengeSubmissionsList,
    response: responseSchemas.challengeSubmissions,
    summary: 'List learner submission history',
    tags: ['Challenges'],
  }),
  operation({
    id: 'getChallengeSubmission',
    method: 'get',
    path: '/challenges/{challengeId}/submissions/{submissionId}',
    request: requestSchemas.challengeSubmissionId,
    response: responseSchemas.challengeSubmission,
    summary: 'Get learner submission detail',
    tags: ['Challenges'],
  }),
  operation({
    id: 'listCourses',
    method: 'get',
    path: '/courses',
    request: requestSchemas.courseList,
    response: responseSchemas.courses,
    security: SECURITY.PUBLIC,
    summary: 'List active public courses',
    tags: ['Courses'],
  }),
  operation({
    id: 'getCourse',
    method: 'get',
    path: '/courses/{courseId}',
    request: requestSchemas.courseId,
    response: responseSchemas.course,
    security: SECURITY.PUBLIC,
    summary: 'Get course details and lesson tree',
    tags: ['Courses'],
  }),
  operation({
    id: 'enrollInCourse',
    method: 'post',
    path: '/courses/{courseId}/enroll',
    request: requestSchemas.courseId,
    response: responseSchemas.enrollment,
    summary: 'Enroll learner in published course',
    tags: ['Courses'],
  }),
  operation({
    id: 'getCourseProgress',
    method: 'get',
    path: '/courses/{courseId}/progress',
    request: requestSchemas.courseId,
    response: responseSchemas.courseProgressOverview,
    summary: 'Get overall course progress overview for learner',
    tags: ['Courses'],
  }),
  operation({
    id: 'getLessonProgress',
    method: 'get',
    path: '/courses/{courseId}/lessons/{contentId}/progress',
    request: requestSchemas.lessonProgress,
    response: responseSchemas.lessonProgress,
    summary: 'Get lesson progress and resume state',
    tags: ['Courses'],
  }),
  operation({
    acceptsBody: true,
    id: 'updateLessonProgress',
    method: 'patch',
    path: '/courses/{courseId}/lessons/{contentId}/progress',
    request: requestSchemas.lessonProgressUpdate,
    response: responseSchemas.lessonProgress,
    summary: 'Update lesson video playback position and watched intervals',
    tags: ['Courses'],
  }),
  operation({ id: 'getProviderDashboard', method: 'get', path: '/lms/provider/organizations/{organizationId}/dashboard', request: requestSchemas.providerOrganization, summary: 'Get provider dashboard aggregates', tags: ['LMS'] }),
  operation({ id: 'listCourseStaff', method: 'get', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/staff', request: requestSchemas.providerCourse, summary: 'List course staff assignments', tags: ['LMS'] }),
  operation({ acceptsBody: true, id: 'setCourseStaffRole', method: 'put', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/staff/{userId}', request: requestSchemas.providerCourseUserBody, summary: 'Assign a course-scoped staff role', tags: ['LMS'] }),
  operation({ id: 'getCourseStructure', method: 'get', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/structure', request: requestSchemas.providerCourse, summary: 'Get the latest editable course structure', tags: ['LMS'] }),
  operation({ acceptsBody: true, id: 'replaceCourseStructure', method: 'put', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/structure', request: requestSchemas.providerCourseBody, summary: 'Save a new draft course structure version', tags: ['LMS'] }),
  operation({ id: 'getCourseRoster', method: 'get', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/roster', request: requestSchemas.providerCourse, summary: 'List course enrollments', tags: ['LMS'] }),
  operation({ acceptsBody: true, id: 'updateCourseEnrollment', method: 'patch', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/enrollments/{enrollmentId}', request: requestSchemas.providerCourseEnrollmentBody, summary: 'Update enrollment state', tags: ['LMS'] }),
  operation({ acceptsBody: true, id: 'inviteCourseLearner', method: 'post', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/invitations', request: requestSchemas.providerCourseBody, status: 201, summary: 'Invite a learner to a private course', tags: ['LMS'] }),
  operation({ id: 'listAssignmentGrading', method: 'get', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/grading', request: requestSchemas.providerCourse, summary: 'List assignment submissions for grading', tags: ['LMS'] }),
  operation({ id: 'listQuizGrading', method: 'get', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/quiz-grading', request: requestSchemas.providerCourse, summary: 'List written quiz attempts for grading', tags: ['LMS'] }),
  operation({ acceptsBody: true, id: 'gradeQuizAttempt', method: 'put', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/quiz-attempts/{attemptId}/grade', request: requestSchemas.providerCourseAttemptBody, summary: 'Grade and optionally release a written quiz attempt', tags: ['LMS'] }),
  operation({ acceptsBody: true, id: 'gradeAssignmentSubmission', method: 'put', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/submissions/{submissionId}/grade', request: requestSchemas.providerCourseSubmissionBody, summary: 'Grade and optionally release an assignment', tags: ['LMS'] }),
  operation({ id: 'listPaymentReviews', method: 'get', path: '/lms/provider/organizations/{organizationId}/payments', request: requestSchemas.providerOrganization, summary: 'List manual payment proofs awaiting review', tags: ['LMS'] }),
  operation({ id: 'getPaymentSettings', method: 'get', path: '/lms/provider/organizations/{organizationId}/payment-settings', request: requestSchemas.providerOrganization, summary: 'Get provider QR-payment configuration', tags: ['LMS'] }),
  operation({ acceptsBody: true, id: 'setPaymentSettings', method: 'put', path: '/lms/provider/organizations/{organizationId}/payment-settings', request: requestSchemas.providerBody, summary: 'Set provider QR-payment configuration', tags: ['LMS'] }),
  operation({ acceptsBody: true, id: 'reviewManualPayment', method: 'put', path: '/lms/provider/organizations/{organizationId}/payments/{orderId}/review', request: requestSchemas.providerPaymentOrderBody, summary: 'Approve, reject, or request more payment evidence', tags: ['LMS'] }),
  operation({ id: 'getProviderCourseAnalytics', method: 'get', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/analytics', request: requestSchemas.providerCourse, summary: 'Get provider-scoped learner progress analytics', tags: ['LMS'] }),
  operation({ id: 'exportProviderCourseAnalytics', method: 'get', path: '/lms/provider/organizations/{organizationId}/courses/{courseId}/analytics.csv', request: requestSchemas.providerCourse, summary: 'Export a bounded audited learner analytics CSV', tags: ['LMS'] }),
  operation({ id: 'acceptCourseInvitation', method: 'post', path: '/lms/invitations/{token}/accept', request: requestSchemas.courseInvitationToken, summary: 'Accept a private course invitation', tags: ['LMS'] }),
  operation({ acceptsBody: true, id: 'submitCourseQuiz', method: 'post', path: '/lms/courses/{courseId}/quizzes/{quizId}/attempts', request: requestSchemas.courseQuizBody, status: 201, summary: 'Submit a course quiz attempt', tags: ['LMS'] }),
  operation({ acceptsBody: true, id: 'submitCourseAssignment', method: 'post', path: '/lms/courses/{courseId}/assignments/{assignmentId}/submissions', request: requestSchemas.courseAssignmentBody, status: 201, summary: 'Submit written work and private files', tags: ['LMS'] }),
  operation({ id: 'createCoursePaymentOrder', method: 'post', path: '/lms/courses/{courseId}/payment-orders', request: requestSchemas.courseId, status: 201, summary: 'Create a manual QR-payment order', tags: ['LMS'] }),
  operation({ acceptsBody: true, id: 'attachCoursePaymentProof', method: 'put', path: '/lms/payment-orders/{orderId}/proof', request: requestSchemas.paymentOrderBody, summary: 'Attach a scanned payment proof', tags: ['LMS'] }),
  operation({ id: 'getLearnerCourseResults', method: 'get', path: '/lms/courses/{courseId}/results', request: requestSchemas.courseId, summary: 'Get released course grades and feedback', tags: ['LMS'] }),
]);

const operationById = new Map(operations.map((entry) => [entry.id, entry]));
if (operationById.size !== operations.length)
  throw new Error('Duplicate API operation identifier.');

function getOperation(id) {
  const found = operationById.get(id);
  if (!found) throw new Error(`Unknown API operation: ${id}`);
  return found;
}

module.exports = { SECURITY, getOperation, operations };
