'use strict';

const { requestSchemas, responseSchemas } = require('./contracts');

const SECURITY = Object.freeze({
  BEARER: Object.freeze([{ bearerAuth: [] }]),
  OPTIONAL_BEARER: Object.freeze([{}, { bearerAuth: [] }]),
  PUBLIC: Object.freeze([]),
  REFRESH_CSRF: Object.freeze([{ csrfHeader: [], refreshCookie: [] }]),
});

function operation({
  acceptsBody = false,
  id,
  method,
  path,
  request,
  response,
  security = SECURITY.BEARER,
  status = 200,
  summary,
  tags,
}) {
  return Object.freeze({
    acceptsBody,
    id,
    method,
    path,
    request,
    response,
    security,
    status,
    summary,
    tags: Object.freeze(tags),
  });
}

const operations = Object.freeze([
  operation({
    id: 'getOpenApiDocument',
    method: 'get',
    path: '/openapi.json',
    request: requestSchemas.noInput,
    response: responseSchemas.openApi,
    security: SECURITY.PUBLIC,
    summary: 'Get the executable OpenAPI 3.1 contract',
    tags: ['Operations'],
  }),
  operation({
    id: 'getLiveness',
    method: 'get',
    path: '/health/live',
    request: requestSchemas.noInput,
    response: responseSchemas.health,
    security: SECURITY.PUBLIC,
    summary: 'Report process liveness without dependency detail',
    tags: ['Operations'],
  }),
  operation({
    id: 'getReadiness',
    method: 'get',
    path: '/health/ready',
    request: requestSchemas.noInput,
    response: responseSchemas.health,
    security: SECURITY.PUBLIC,
    summary: 'Report aggregate serving readiness',
    tags: ['Operations'],
  }),
  operation({
    id: 'getDependencyReadiness',
    method: 'get',
    path: '/health/dependencies',
    request: requestSchemas.noInput,
    response: responseSchemas.healthDependencies,
    summary: 'Report redacted dependency states to a superadmin',
    tags: ['Operations'],
  }),
  operation({
    acceptsBody: true,
    id: 'register',
    method: 'post',
    path: '/auth/register',
    request: requestSchemas.identityRegister,
    response: responseSchemas.accessSession,
    security: SECURITY.PUBLIC,
    status: 201,
    summary: 'Create a learner account and web session',
    tags: ['Identity'],
  }),
  operation({
    acceptsBody: true,
    id: 'login',
    method: 'post',
    path: '/auth/login',
    request: requestSchemas.identityLogin,
    response: responseSchemas.accessSession,
    security: SECURITY.PUBLIC,
    summary: 'Create a web session with local credentials',
    tags: ['Identity'],
  }),
  operation({
    id: 'refreshSession',
    method: 'post',
    path: '/auth/refresh',
    request: requestSchemas.empty,
    response: responseSchemas.accessSession,
    security: SECURITY.REFRESH_CSRF,
    summary: 'Rotate the refresh token and issue an access token',
    tags: ['Identity'],
  }),
  operation({
    id: 'logout',
    method: 'post',
    path: '/auth/logout',
    request: requestSchemas.empty,
    security: SECURITY.REFRESH_CSRF,
    status: 204,
    summary: 'Revoke the current refresh session',
    tags: ['Identity'],
  }),
  operation({
    id: 'logoutAll',
    method: 'post',
    path: '/auth/logout-all',
    request: requestSchemas.empty,
    status: 204,
    summary: 'Revoke every session for the authenticated user',
    tags: ['Identity'],
  }),
  operation({
    id: 'requestEmailVerification',
    method: 'post',
    path: '/auth/email/verify/request',
    request: requestSchemas.empty,
    response: responseSchemas.message,
    status: 202,
    summary: 'Queue an email-verification token when needed',
    tags: ['Identity'],
  }),
  operation({
    acceptsBody: true,
    id: 'confirmEmailVerification',
    method: 'post',
    path: '/auth/email/verify/confirm',
    request: requestSchemas.identityConfirmToken,
    response: responseSchemas.user,
    security: SECURITY.PUBLIC,
    summary: 'Consume an email-verification token',
    tags: ['Identity'],
  }),
  operation({
    acceptsBody: true,
    id: 'requestPasswordReset',
    method: 'post',
    path: '/auth/password/forgot',
    request: requestSchemas.identityForgotPassword,
    response: responseSchemas.message,
    security: SECURITY.PUBLIC,
    status: 202,
    summary: 'Queue a password-reset token without account disclosure',
    tags: ['Identity'],
  }),
  operation({
    acceptsBody: true,
    id: 'resetPassword',
    method: 'post',
    path: '/auth/password/reset',
    request: requestSchemas.identityResetPassword,
    security: SECURITY.PUBLIC,
    status: 204,
    summary: 'Consume a password-reset token and revoke sessions',
    tags: ['Identity'],
  }),
  operation({
    id: 'startGoogleLogin',
    method: 'get',
    path: '/auth/google/start',
    request: requestSchemas.googleStart,
    security: SECURITY.PUBLIC,
    status: 302,
    summary: 'Begin the Google authorization-code flow',
    tags: ['Identity'],
  }),
  operation({
    id: 'completeGoogleLogin',
    method: 'get',
    path: '/auth/google/callback',
    request: requestSchemas.googleCallback,
    security: SECURITY.PUBLIC,
    status: 302,
    summary: 'Complete the Google authorization-code flow',
    tags: ['Identity'],
  }),
  operation({
    id: 'getMe',
    method: 'get',
    path: '/me',
    request: requestSchemas.noInput,
    response: responseSchemas.user,
    summary: 'Get the authenticated user',
    tags: ['Identity'],
  }),
  operation({
    id: 'listMySessions',
    method: 'get',
    path: '/me/sessions',
    request: requestSchemas.noInput,
    response: responseSchemas.sessions,
    summary: 'List sessions for the authenticated user',
    tags: ['Identity'],
  }),
  operation({
    id: 'revokeMySession',
    method: 'delete',
    path: '/me/sessions/{sessionId}',
    request: requestSchemas.sessionId,
    status: 204,
    summary: 'Revoke one owned session',
    tags: ['Identity'],
  }),
  operation({
    id: 'listMyOrganizations',
    method: 'get',
    path: '/organizations',
    request: requestSchemas.noInput,
    response: responseSchemas.organizations,
    summary: 'List active organization memberships',
    tags: ['Organizations'],
  }),
  operation({
    acceptsBody: true,
    id: 'createOrganization',
    method: 'post',
    path: '/organizations',
    request: requestSchemas.organizationCreate,
    response: responseSchemas.organizationCreated,
    status: 201,
    summary: 'Create an organization with an owner membership',
    tags: ['Organizations'],
  }),
  operation({
    id: 'acceptOrganizationInvitation',
    method: 'post',
    path: '/organization-invitations/{token}/accept',
    request: requestSchemas.organizationInvitationAccept,
    response: responseSchemas.invitationAccepted,
    summary: 'Accept an organization invitation',
    tags: ['Organizations'],
  }),
  operation({
    id: 'listProviderVerificationReviews',
    method: 'get',
    path: '/admin/provider-verifications',
    request: requestSchemas.organizationReviews,
    response: responseSchemas.reviews,
    summary: 'List provider verification reviews',
    tags: ['Organizations', 'Administration'],
  }),
  operation({
    acceptsBody: true,
    id: 'decideProviderVerification',
    method: 'post',
    path: '/admin/provider-verifications/{reviewId}/decision',
    request: requestSchemas.organizationDecision,
    response: responseSchemas.verification,
    summary: 'Approve or reject a provider verification',
    tags: ['Organizations', 'Administration'],
  }),
  operation({
    id: 'getOrganization',
    method: 'get',
    path: '/organizations/{organizationId}',
    request: requestSchemas.organizationId,
    response: responseSchemas.organization,
    security: SECURITY.OPTIONAL_BEARER,
    summary: 'Get a public or authorized private organization',
    tags: ['Organizations'],
  }),
  operation({
    acceptsBody: true,
    id: 'updateOrganization',
    method: 'patch',
    path: '/organizations/{organizationId}',
    request: requestSchemas.organizationUpdate,
    response: responseSchemas.organization,
    summary: 'Update organization fields with optimistic concurrency',
    tags: ['Organizations'],
  }),
  operation({
    id: 'listOrganizationMembers',
    method: 'get',
    path: '/organizations/{organizationId}/members',
    request: requestSchemas.organizationMembers,
    response: responseSchemas.memberships,
    summary: 'List authorized organization members',
    tags: ['Organizations'],
  }),
  operation({
    acceptsBody: true,
    id: 'inviteOrganizationMember',
    method: 'post',
    path: '/organizations/{organizationId}/invitations',
    request: requestSchemas.organizationInvitation,
    response: responseSchemas.invitation,
    status: 201,
    summary: 'Invite a member into an organization role',
    tags: ['Organizations'],
  }),
  operation({
    acceptsBody: true,
    id: 'updateOrganizationMember',
    method: 'patch',
    path: '/organizations/{organizationId}/members/{userId}',
    request: requestSchemas.organizationMemberMutation,
    response: responseSchemas.membership,
    summary: 'Update an organization membership',
    tags: ['Organizations'],
  }),
  operation({
    id: 'removeOrganizationMember',
    method: 'delete',
    path: '/organizations/{organizationId}/members/{userId}',
    request: {
      body: requestSchemas.empty.body,
      params: requestSchemas.organizationMemberMutation.params,
    },
    status: 204,
    summary: 'Revoke an organization membership',
    tags: ['Organizations'],
  }),
  operation({
    acceptsBody: true,
    id: 'submitProviderVerification',
    method: 'post',
    path: '/organizations/{organizationId}/verification',
    request: requestSchemas.organizationVerification,
    response: responseSchemas.verification,
    status: 201,
    summary: 'Submit an organization for provider verification',
    tags: ['Organizations'],
  }),
  operation({
    id: 'listAuthorityAuditEvents',
    method: 'get',
    path: '/admin/audit-events',
    request: requestSchemas.authorityAuditList,
    response: responseSchemas.auditEvents,
    summary: 'List bounded authority audit events',
    tags: ['Administration'],
  }),
  operation({
    id: 'listAuthorityUsers',
    method: 'get',
    path: '/admin/users',
    request: requestSchemas.authorityUserList,
    response: responseSchemas.authorityUsers,
    summary: 'List bounded platform authority users',
    tags: ['Administration'],
  }),
  operation({
    acceptsBody: true,
    id: 'changePlatformRole',
    method: 'patch',
    path: '/admin/users/{userId}/platform-role',
    request: requestSchemas.authorityRoleChange,
    response: responseSchemas.authorityChange,
    summary: 'Change a platform role with an audited revision check',
    tags: ['Administration'],
  }),
  operation({
    acceptsBody: true,
    id: 'changeAccountStatus',
    method: 'patch',
    path: '/admin/users/{userId}/status',
    request: requestSchemas.authorityStatusChange,
    response: responseSchemas.authorityChange,
    summary: 'Change account status with an audited revision check',
    tags: ['Administration'],
  }),
  operation({
    acceptsBody: true,
    id: 'transferOrganizationOwnership',
    method: 'post',
    path: '/organizations/{organizationId}/ownership-transfer',
    request: requestSchemas.authorityTransfer,
    response: responseSchemas.ownershipTransfer,
    summary: 'Atomically transfer organization ownership',
    tags: ['Administration', 'Organizations'],
  }),
  operation({
    acceptsBody: true,
    id: 'createFileUploadIntent',
    method: 'post',
    path: '/files/upload-intents',
    request: requestSchemas.fileUploadIntent,
    response: responseSchemas.uploadIntent,
    status: 201,
    summary: 'Create a bounded direct-upload intent',
    tags: ['Files'],
  }),
  operation({
    id: 'getFileMetadata',
    method: 'get',
    path: '/files/{fileId}',
    request: requestSchemas.fileId,
    response: responseSchemas.file,
    summary: 'Get authorized file metadata',
    tags: ['Files'],
  }),
  operation({
    id: 'completeFileUpload',
    method: 'post',
    path: '/files/{fileId}/complete',
    request: requestSchemas.fileIdMutation,
    response: responseSchemas.file,
    summary: 'Verify uploaded object metadata before scan',
    tags: ['Files'],
  }),
  operation({
    id: 'createFileDownload',
    method: 'post',
    path: '/files/{fileId}/download',
    request: requestSchemas.fileIdMutation,
    response: responseSchemas.download,
    summary: 'Create a short-lived authorized download grant',
    tags: ['Files'],
  }),
  operation({
    acceptsBody: true,
    id: 'setFileVisibility',
    method: 'patch',
    path: '/files/{fileId}/visibility',
    request: requestSchemas.fileVisibility,
    response: responseSchemas.file,
    summary: 'Change file visibility within its purpose policy',
    tags: ['Files'],
  }),
  operation({
    id: 'deleteFile',
    method: 'delete',
    path: '/files/{fileId}',
    request: requestSchemas.fileIdMutation,
    status: 204,
    summary: 'Revoke access and request object deletion',
    tags: ['Files'],
  }),
]);

const operationById = new Map(operations.map((entry) => [entry.id, entry]));
if (operationById.size !== operations.length)
  throw new Error('Duplicate API operation identifier.');

function getOperation(id) {
  const found = operationById.get(id);
  if (!found) throw new Error(`Unknown API operation: ${id}`);
  return found;
}

module.exports = { SECURITY, getOperation, operations };
